### ISSUE TITLE
(global 'startTimer')

### ISSUE THREAD

**Issue by iHemeda** [pushkart2/qb-dumpster#1]
[  script:qb-dumpster] SCRIPT ERROR: @qb-dumpster/server/server.lua:6: attempt to call a nil value (global 'startTimer')

**Comment by pushkart2** [comment]
Reach out to me on discord - ```Snipe#0168```

**Comment by pushkart2** [comment]
do a pull again

**Comment by iHemeda** [comment]
Thanks @pushkart2 you are fixed it now, no errors appear
