### ISSUE TITLE
Error client.lua:91 Nil value on QBCore

### ISSUE THREAD

**Issue by tornados1000** [pushkart2/qb-dumpster#9]
![image](https://user-images.githubusercontent.com/28545453/135773410-d23e9de0-132e-4286-b359-0b950e0a8e3e.png)
Hello there. The scritps doesn't work and needs to get fixed

**Comment by SP13RS** [comment]
take out QBCore= nill replace it with "local QBCore = exports['qb-core']:GetCoreObject() " in both client and server

**Comment by SP13RS** [comment]
> ![image](https://user-images.githubusercontent.com/28545453/135773410-d23e9de0-132e-4286-b359-0b950e0a8e3e.png) Hello there. The scritps doesn't work and needs to get fixed

take out QBCore= nill replace it with "local QBCore = exports['qb-core']:GetCoreObject() " in both client and server

**Comment by tornados1000** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/28545453/135773410-d23e9de0-132e-4286-b359-0b950e0a8e3e.png) Hello there. The scritps doesn't work and needs to get fixed
> 
> take out QBCore= nill replace it with "local QBCore = exports['qb-core']:GetCoreObject() " in both client and server

Replaced as you mentioned and it's working. Thank you for your assistance :)
